[project]
name = "my-dbt-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Kartz429", email = "kartiksalunkhe01@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "dbt-core>=1.12.5",
    "dbt-databricks>=1.10.9",
]

[project.scripts]
my-dbt-project = "my_dbt_project:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
